builds:
  - env:
    - CGO_ENABLED=0
    binary: helmet-controller
    main: ./
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries: 
      - helmet-controller
    skip_push: false
    dockerfile: Dockerfile
    # Template of the docker tag. Defaults to `{{ .Version }}`.
    # Other allowed fields are:
    # - `.Commint`
    # - `.Tag`
    # - `.Major`
    # - `.Minor`
    # - `.Patch`
    # - `.Env.VARIABLE_NAME`
    image_templates: 
      - "maartje/helmet-controller:amd64-{{ .Tag }}"
      - "maartje/helmet-controller:amd64-{{ .Major }}"
      - "maartje/helmet-controller:amd64-latest"
  - goos: linux
    goarch: arm64
    goarm: ''
    binaries: 
      - helmet-controller
    image_templates: 
      - "maartje/helmet-controller:arm64-{{ .Tag }}"
      - "maartje/helmet-controller:arm64-{{ .Major }}"
      - "maartje/helmet-controller:arm64-latest"
    skip_push: false
    dockerfile: Dockerfile
    # Template of the docker tag. Defaults to `{{ .Version }}`.
    # Other allowed fields are:
    # - `.Commint`
    # - `.Tag`
    # - `.Major`
    # - `.Minor`
    # - `.Patch`
    # - `.Env.VARIABLE_NAME`
  - goos: linux
    goarch: arm
    goarm: '6'
    binaries: 
      - helmet-controller
    skip_push: false
    dockerfile: Dockerfile
    # Template of the docker tag. Defaults to `{{ .Version }}`.
    # Other allowed fields are:
    # - `.Commint`
    # - `.Tag`
    # - `.Major`
    # - `.Minor`
    # - `.Patch`
    # - `.Env.VARIABLE_NAME`
    image_templates: 
      - "maartje/helmet-controller:armhf-{{ .Tag }}"
      - "maartje/helmet-controller:armhf-{{ .Major }}"
      - "maartje/helmet-controller:armhf-latest"