language: go
go:
- 1.x
addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm

# needed for the docker pipe
services:
- docker

script:
- go test ./...

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux